services:

  postgres:
    image : postgres:18
    environment: 
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    
    volumes: 
      - postgres_data:/var/lib/postgresql
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  airflow-init:
    image: ${AIRFLOW_IMAGE_NAME}
    
    depends_on:
      postgres:
        condition:
          service_healthy
    
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD_URI}@postgres:5432/${AIRFLOW_DB_NAME}

      
    command: db migrate

  airflow-dag-processor:
    image: ${AIRFLOW_IMAGE_NAME}

    depends_on:
      airflow-init:
        condition:
          service_completed_successfully
    
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD_URI}@postgres:5432/${AIRFLOW_DB_NAME}

    volumes:
      - ./dags:/opt/airflow/dags
    
    command: 
      - dag-processor

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE_NAME}

    depends_on:
      airflow-init:
        condition:
          service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD_URI}@postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      
    command: scheduler

    volumes:
      - ./dags:/opt/airflow/dags

  airflow-api-server:  
    image: ${AIRFLOW_IMAGE_NAME}

    depends_on:
      airflow-init:
        condition:
          service_completed_successfully
    
    ports:
      - "8080:8080"

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD_URI}@postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      
    command: api-server

    volumes:
      - ./dags:/opt/airflow/dags


volumes:
  postgres_data: 
    

      